# Generated by Django 4.1.7 on 2023-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPromt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('prompt_sent', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('sv_scheduled', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_prompts',
            },
        ),
    ]
